LOAD DATA LOCAL INFILE 'user.tsv' INTO TABLE user LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'box.tsv' INTO TABLE box LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'match.tsv' INTO TABLE match LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'interaction.tsv' INTO TABLE interaction LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'socials.tsv' INTO TABLE socials LINES TERMINATED BY '\n';
