SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE genre;
SET FOREIGN_KEY_CHECKS = 1;
INSERT INTO genre (genre) VALUES ('Rock');
INSERT INTO genre (genre) VALUES ('Pop');
INSERT INTO genre (genre) VALUES ('Hip Hop');
INSERT INTO genre (genre) VALUES ('Jazz');
INSERT INTO genre (genre) VALUES ('Blues');
INSERT INTO genre (genre) VALUES ('Electronic');
INSERT INTO genre (genre) VALUES ('Folk');
INSERT INTO genre (genre) VALUES ('R&b');
INSERT INTO genre (genre) VALUES ('Country');
INSERT INTO genre (genre) VALUES ('Soul');
INSERT INTO genre (genre) VALUES ('Funk');
INSERT INTO genre (genre) VALUES ('Reggae');
INSERT INTO genre (genre) VALUES ('Latin');
INSERT INTO genre (genre) VALUES ('Classical');
INSERT INTO genre (genre) VALUES ('World');
INSERT INTO genre (genre) VALUES ('Edm');
INSERT INTO genre (genre) VALUES ('Heavy metal');
INSERT INTO genre (genre) VALUES ('Alternative');
INSERT INTO genre (genre) VALUES ('Indie');
INSERT INTO genre (genre) VALUES ('Punk');
INSERT INTO genre (genre) VALUES ('Grunge');
INSERT INTO genre (genre) VALUES ('Folk Rock');
INSERT INTO genre (genre) VALUES ('Country Rock');
INSERT INTO genre (genre) VALUES ('Pop Rock');
INSERT INTO genre (genre) VALUES ('Soft Rock');
INSERT INTO genre (genre) VALUES ('Hard Rock');
INSERT INTO genre (genre) VALUES ('Metal');
INSERT INTO genre (genre) VALUES ('Gothic');
INSERT INTO genre (genre) VALUES ('Industrial');
INSERT INTO genre (genre) VALUES ('Alternative Rock');
INSERT INTO genre (genre) VALUES ('Emo');
INSERT INTO genre (genre) VALUES ('Hardcore');
INSERT INTO genre (genre) VALUES ('Post-hardcore');
INSERT INTO genre (genre) VALUES ('Screamo');
INSERT INTO genre (genre) VALUES ('Punk Rock');
INSERT INTO genre (genre) VALUES ('Ska');
INSERT INTO genre (genre) VALUES ('Ska Punk');
INSERT INTO genre (genre) VALUES ('Reggae Rock');
INSERT INTO genre (genre) VALUES ('Dub');
INSERT INTO genre (genre) VALUES ('Roots reggae');
INSERT INTO genre (genre) VALUES ('Dancehall');
INSERT INTO genre (genre) VALUES ('Soca');
INSERT INTO genre (genre) VALUES ('Calypso');
INSERT INTO genre (genre) VALUES ('Salsa');
INSERT INTO genre (genre) VALUES ('Merengue');
INSERT INTO genre (genre) VALUES ('Bachata');
INSERT INTO genre (genre) VALUES ('Latin Pop');
INSERT INTO genre (genre) VALUES ('Latin Rock');
INSERT INTO genre (genre) VALUES ('Latin Jazz');
INSERT INTO genre (genre) VALUES ('Latin electronic');
INSERT INTO genre (genre) VALUES ('Afrobeat');
INSERT INTO genre (genre) VALUES ('Highlife');
INSERT INTO genre (genre) VALUES ('Soukous');
INSERT INTO genre (genre) VALUES ('Kwaito');
INSERT INTO genre (genre) VALUES ('Gqom');
INSERT INTO genre (genre) VALUES ('Zouk');
INSERT INTO genre (genre) VALUES ('Bollywood');
INSERT INTO genre (genre) VALUES ('Bhangra');
INSERT INTO genre (genre) VALUES ('Qawwali');
INSERT INTO genre (genre) VALUES ('Ghazal');
INSERT INTO genre (genre) VALUES ('Arab Pop');
INSERT INTO genre (genre) VALUES ('Raï');
INSERT INTO genre (genre) VALUES ('Andalusian Classical');
INSERT INTO genre (genre) VALUES ('Flamenco');
INSERT INTO genre (genre) VALUES ('Fado');
INSERT INTO genre (genre) VALUES ('Tango');
INSERT INTO genre (genre) VALUES ('Samba');
INSERT INTO genre (genre) VALUES ('Bossa Nova');
INSERT INTO genre (genre) VALUES ('Mambo');
INSERT INTO genre (genre) VALUES ('Sertanejo');
INSERT INTO genre (genre) VALUES ('Forró');
INSERT INTO genre (genre) VALUES ('Cumbia');
INSERT INTO genre (genre) VALUES ('Reggaeton');
INSERT INTO genre (genre) VALUES ('Dembow');
INSERT INTO genre (genre) VALUES ('Moombahton');
INSERT INTO genre (genre) VALUES ('Merengue Electronico');
INSERT INTO genre (genre) VALUES ('Trance');
INSERT INTO genre (genre) VALUES ('House');
INSERT INTO genre (genre) VALUES ('Techno');
INSERT INTO genre (genre) VALUES ('Drum and Bass');
INSERT INTO genre (genre) VALUES ('Dubstep');
INSERT INTO genre (genre) VALUES ('Electro');
INSERT INTO genre (genre) VALUES ('Garage');
INSERT INTO genre (genre) VALUES ('Grime');
INSERT INTO genre (genre) VALUES ('Hip Hop Beats');
INSERT INTO genre (genre) VALUES ('Trap');
INSERT INTO genre (genre) VALUES ('Bass');
INSERT INTO genre (genre) VALUES ('Electro House');
INSERT INTO genre (genre) VALUES ('Electro Swing');
INSERT INTO genre (genre) VALUES ('Jungle');
INSERT INTO genre (genre) VALUES ('Breakbeat');
INSERT INTO genre (genre) VALUES ('Acid Jazz');
INSERT INTO genre (genre) VALUES ('Ambient');
INSERT INTO genre (genre) VALUES ('Downtempo');
INSERT INTO genre (genre) VALUES ('Glitch');
INSERT INTO genre (genre) VALUES ('Idm');
INSERT INTO genre (genre) VALUES ('Chillout');
INSERT INTO genre (genre) VALUES ('Lounge');
INSERT INTO genre (genre) VALUES ('New Age');
INSERT INTO genre (genre) VALUES ('Psychedelic');
INSERT INTO genre (genre) VALUES ('Space music');
